objects_src = [
	'abstract.c',
	'boolobject.c',
	'bytearrayobject.c',
	'bytes_methods.c',
	'bytesobject.c',
	'call.c',
	'capsule.c',
	'cellobject.c',
	'classobject.c',
	'codeobject.c',
	'complexobject.c',
	'descrobject.c',
	'dictobject.c',
	'enumobject.c',
	'exceptions.c',
	'fileobject.c',
	'floatobject.c',
	'frameobject.c',
	'funcobject.c',
	'genericaliasobject.c',
	'genobject.c',
	'iterobject.c',
	'listobject.c',
	'longobject.c',
	'memoryobject.c',
	'methodobject.c',
	'moduleobject.c',
	'namespaceobject.c',
	'object.c',
	'obmalloc.c',
	'odictobject.c',
	'picklebufobject.c',
	'rangeobject.c',
	'setobject.c',
	'sliceobject.c',
	'structseq.c',
	'tupleobject.c',
	'typeobject.c',
	'typevarobject.c',
	'unicodectype.c',
	'unicodeobject.c',
	'unionobject.c',
	'weakrefobject.c'
]

python_objects_lib = static_library('libpython-objects', objects_src, pyconfig,
	c_args: ['-DPy_BUILD_CORE'],
	include_directories: [ inc, private_inc, get_option('allocator') == 'mimalloc' ? mimalloc_inc : [] ]
)
