lib_subdirs = [
	'asyncio',
	'collections',
	'concurrent', 'concurrent/futures',
	'ctypes', 'ctypes/macholib',
	'curses',
	'dbm',
	'email', 'email/mime',
	'encodings',
	'ensurepip', 'ensurepip/_bundled',
	'html',
	'http',
	'idlelib', 'idlelib/Icons',
	'importlib', 'importlib/resources', 'importlib/metadata',
	'json',
	'logging',
	'multiprocessing', 'multiprocessing/dummy',
	'pathlib',
	'pydoc_data',
	're',
	'site-packages',
	'sqlite3',
	'sysconfig',
	'tkinter',
	'tomllib',
	'turtledemo',
	'unittest',
	'urllib',
	'venv', 'venv/scripts', 'venv/scripts/common', 'venv/scripts/posix',
	'wsgiref',
	'xml', 'xml/dom', 'xml/etree', 'xml/parsers', 'xml/sax',
	'xmlrpc',
	'zipfile', 'zipfile/_path',
	'zoneinfo',
	'_pyrepl',
	'__phello__'
]

lib_files = [	
	'abc.py',
	'_aix_support.py',
	'_android_support.py',
	'annotationlib.py',
	'antigravity.py',
	'_apple_support.py',
	'argparse.py',
	'ast.py',
	'base64.py',
	'bdb.py',
	'bisect.py',
	'bz2.py',
	'calendar.py',
	'cmd.py',
	'codecs.py',
	'codeop.py',
	'code.py',
	'_collections_abc.py',
	'_colorize.py',
	'colorsys.py',
	'_compat_pickle.py',
	'compileall.py',
	'_compression.py',
	'configparser.py',
	'contextlib.py',
	'contextvars.py',
	'copy.py',
	'copyreg.py',
	'cProfile.py',
	'csv.py',
	'dataclasses.py',
	'datetime.py',
	'decimal.py',
	'difflib.py',
	'dis.py',
	'doctest.py',
	'enum.py',
	'filecmp.py',
	'fileinput.py',
	'fnmatch.py',
	'fractions.py',
	'ftplib.py',
	'functools.py',
	'__future__.py',
	'genericpath.py',
	'getopt.py',
	'getpass.py',
	'gettext.py',
	'glob.py',
	'graphlib.py',
	'gzip.py',
	'hashlib.py',
	'heapq.py',
	'__hello__.py',
	'hmac.py',
	'imaplib.py',
	'inspect.py',
	'io.py',
	'_ios_support.py',
	'ipaddress.py',
	'keyword.py',
	'linecache.py',
	'locale.py',
	'lzma.py',
	'mailbox.py',
	'_markupbase.py',
	'mimetypes.py',
	'modulefinder.py',
	'netrc.py',
	'ntpath.py',
	'nturl2path.py',
	'numbers.py',
	'_opcode_metadata.py',
	'opcode.py',
	'operator.py',
	'optparse.py',
	'os.py',
	'_osx_support.py',
	'pdb.py',
	'pickle.py',
	'pickletools.py',
	'pkgutil.py',
	'platform.py',
	'plistlib.py',
	'poplib.py',
	'posixpath.py',
	'pprint.py',
	'profile.py',
	'pstats.py',
	'pty.py',
	'_py_abc.py',
	'pyclbr.py',
	'py_compile.py',
	'_pydatetime.py',
	'_pydecimal.py',
	'pydoc.py',
	'_pyio.py',
	'_pylong.py',
	'queue.py',
	'quopri.py',
	'random.py',
	'reprlib.py',
	'rlcompleter.py',
	'runpy.py',
	'sched.py',
	'secrets.py',
	'selectors.py',
	'shelve.py',
	'shlex.py',
	'shutil.py',
	'signal.py',
	'_sitebuiltins.py',
	'site.py',
	'smtplib.py',
	'socket.py',
	'socketserver.py',
	'sre_compile.py',
	'sre_constants.py',
	'sre_parse.py',
	'ssl.py',
	'statistics.py',
	'stat.py',
	'stringprep.py',
	'string.py',
	'_strptime.py',
	'struct.py',
	'subprocess.py',
	'symtable.py',
	'tabnanny.py',
	'tarfile.py',
	'tempfile.py',
	'textwrap.py',
	'this.py',
	'_threading_local.py',
	'threading.py',
	'timeit.py',
	'tokenize.py',
	'token.py',
	'traceback.py',
	'tracemalloc.py',
	'trace.py',
	'tty.py',
	'turtle.py',
	'types.py',
	'typing.py',
	'uuid.py',
	'warnings.py',
	'wave.py',
	'weakref.py',
	'_weakrefset.py',
	'webbrowser.py',
	'zipapp.py',
	'zipimport.py',
]

foreach dir : lib_subdirs
	install_subdir(dir,
		install_dir: get_option('libdir') / 'python@0@'.format(py_release),
		install_tag: 'runtime',
		strip_directory: false,
		exclude_directories: '__pycache__'
	)
endforeach

foreach file : lib_files
	install_data(file,
		install_dir: get_option('libdir') / 'python@0@'.format(py_release),
		install_tag: 'runtime',
		preserve_path: true
	)
endforeach

# TODO: generate pyc to install
