python_src = [
	'Python-ast.c',
	'Python-tokenize.c',
	'_warnings.c',
	'asdl.c',
	'assemble.c',
	'ast.c',
	'ast_opt.c',
	'ast_unparse.c',
	'bltinmodule.c',
	'bootstrap_hash.c',
	'brc.c',
	#'bytecodes.c',
	'ceval.c',
	'ceval_gil.c',
	'codecs.c',
	'codegen.c',
	'compile.c',
	'context.c',
	'critical_section.c',
	'crossinterp.c',
	'dtoa.c',
	'dup2.c',
	'dynamic_annotations.c',
	'errors.c',
	'fileutils.c',
	'flowgraph.c',
	'formatter_unicode.c',
	'frame.c',
	'frozenmain.c',
	'future.c',
	'gc.c',
	'gc_free_threading.c',
	'gc_gil.c',
	'getargs.c',
	'getcompiler.c',
	'getcopyright.c',
	'getopt.c',
	'getplatform.c',
	'getversion.c',
	'hamt.c',
	'hashtable.c',
	'import.c',
	'importdl.c',
	'index_pool.c',
	'initconfig.c',
	'instruction_sequence.c',
	'instrumentation.c',
	'interpconfig.c',
	'intrinsics.c',
	'jit.c',
	'legacy_tracing.c',
	'lock.c',
	'marshal.c',
	'modsupport.c',
	'mysnprintf.c',
	'mystrtoul.c',
	'object_stack.c',
	'optimizer.c',
	'optimizer_analysis.c',
	#'optimizer_bytecodes.c',
	'optimizer_symbols.c',
	'parking_lot.c',
	'pathconfig.c',
	'perf_jit_trampoline.c',
	'perf_trampoline.c',
	'preconfig.c',
	'pyarena.c',
	'pyctype.c',
	'pyfpe.c',
	'pyhash.c',
	'pylifecycle.c',
	'pymath.c',
	'pystate.c',
	'pystrcmp.c',
	'pystrhex.c',
	'pystrtod.c',
	'pythonrun.c',
	'pytime.c',
	'qsbr.c',
	'specialize.c',
	'stackrefs.c',
	'structmember.c',
	'suggestions.c',
	'symtable.c',
	'sysmodule.c',
	'thread.c',
	'traceback.c',
	'tracemalloc.c',
	'uniqueid.c',
]

python_src += 'asm_trampoline.S'

if ['cygwin', 'windows'].contains(host_machine.system())
	python_src += 'dynload_win.c'
elif ['android', 'linux', 'darwin'].contains(host_machine.system())
	python_src += 'dynload_shlib.c'
elif false
	python_src += 'dynload_hpux.c'
else
	python_src += 'dynload_stub.c'
endif

if ['wasm32', 'wasm64'].contains(host_machine.cpu())
	python_src += [
		'emscripten_signal.c',
		'emscripten_trampoline.c'
	]
endif

python_python_lib_omit_frozen = static_library('python', python_src,
	c_args: [ '-DPy_BUILD_CORE' ],
	include_directories: [ inc, private_inc ],
	link_with: [ python_objects_lib, python_parser_lib ],
)
